package impl;

import semweb.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultCourse <br>
 * @version generated on Sat Apr 03 10:21:32 IST 2021 by prateksha
 */
public class DefaultCourse extends WrappedIndividualImpl implements Course {

    public DefaultCourse(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
